### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379                                                                                      wildduck-1  |   full_message: 'MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:2

### ISSUE THREAD

**Issue by psschand16** [zone-eu/wildduck#807]
The connection to mongo and redis is refused with default docker compose file

**Comment by narayanapk** [comment]
Somehow, the **CMD_ARGS** environment variable overrides are not honoured. The server appears to be still using default configuration.

However , passing the overrides the following way seem to be working.

```yaml
environment:
        APPCONF_dbs_mongo: mongodb://mongo:27017/wildduck
        APPCONF_dbs_redis: redis://redis:6379/3
        APPCONF_api_host: 0.0.0.0
        APPCONF_api_accessToken: PLEASE_CHANGE_ME
```
